return {
  {
    "Mr-LLLLL/interestingwords.nvim",
    opts = {
      -- colors = {
      --   "#ff4538",
      --   "#ffe438",
      --   "#7bff38",
      --   "#38ff95",
      --   "#38caff",
      --   "#4538ff",
      --   "#e438ff",
      --   "#ff387b",
      --   "#ff9538",
      --   "#caff38",
      --   "#9538ff",
      -- },
      -- --"#aeee00", "#ff0000", "#0000ff", "#b88823", "#ffa724", "#ff2c4b" },
      search_count = false,
      navigation = true,
      scroll_center = true,
      search_key = false,
      cancel_search_key = false,
      color_key = "<leader>k",
      cancel_color_key = "<leader>K",
      select_mode = "loop",
    },
    keys = { -- added for lazyloading
      "<leader>m",
      "<leader>M",
      "<leader>k",
      "<leader>K",
    },
  },
}
